#cod.jdbc.url=jdbc:phoenix:ip-10-10-22-107.us-east-2.compute.internal:2181:/hbase
cod.jdbc.url=jdbc:phoenix:cod-1fn7p04w849aa-leader0.ps-sandb.a465-9q4k.cloudera.site,cod-1fn7p04w849aa-master0.ps-sandb.a465-9q4k.cloudera.site,cod-1fn7p04w849aa-master1.ps-sandb.a465-9q4k.cloudera.site:2181:/hbase
