# Secure HBase credentials, core-site.xml and hbase-site.xml are expected to be in the classpath
# It's used for secure HBase only and ignored otherwise
# principal: omid_hbase_client
# keytab: /path/to/hbase/client/keytab

omidClientConfiguration: !!org.apache.omid.tso.client.OmidClientConfiguration
  connectionString: "cod--xkqqx865u1bl-master0.ps-sandb.a465-9q4k.cloudera.site:2181,cod--xkqqx865u1bl-master1.ps-sandb.a465-9q4k.cloudera.site:2181,cod--xkqqx865u1bl-leader0.ps-sandb.a465-9q4k.cloudera.site:2181"
  connectionType: !!org.apache.omid.tso.client.OmidClientConfiguration$ConnType HA
  zkCurrentTsoPath: "/current-tso"
  zkNamespace: "omid"
  tlsEnabled: true
  enabledProtocols: "TLSv1.2"
  trustStoreLocation: "/var/lib/cloudera-scm-agent/agent-cert/cm-auto-global_truststore.jks"
  trustStorePassword: "bSVAvcrR0XAC5yb4F1422Hg507"
  trustStoreType: "jks"

metrics: !!org.apache.omid.metrics.CodahaleMetricsProvider [
!!org.apache.omid.metrics.CodahaleMetricsConfig {
  outputFreqInSecs: 15,
  reporters: !!set {
    !!org.apache.omid.metrics.CodahaleMetricsConfig$Reporter CSV
  },
  csvDir: "csvMetrics",
  prefix: "somePrefix",
}
]
